export const FETCH_ALL_ADMINS = 'FETCH_ALL_ADMINS'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const FETCH_APPROVED_USERS = 'FETCH_APPROVED_USERS'
export const FETCH_UNAPPROVED_USERS = 'FETCH_UNAPPROVED_USERS'