export const FETCH_ALL_ADMINS_USERS = 'FETCH_ALL_ADMINS_USERS'
export const FETCH_ALL_ADMINS = 'FETCH_ALL_ADMINS'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const FETCH_APPROVED_USERS = 'FETCH_APPROVED_USERS'
export const FETCH_UNAPPROVED_USERS = 'FETCH_UNAPPROVED_USERS'

export const FETCH_ALL_LISTINGS = 'FETCH_ALL_LISTINGS'
export const FETCH_APPROVED_LISTINGS = 'FETCH_APPROVED_LISTINGS'
export const FETCH_UNAPPROVED_LISTINGS = 'FETCH_UNAPPROVED_LISTINGS'

export const FETCH_BOARD_MEMBERS = 'FETCH_BOARD_MEMBERS'
export const FETCH_BOARD_ROLES = 'FETCH_BOARD_ROLES'