export const FETCH_POPULAR_LISTING = 'FETCH_POPULAR_LISTING'
export const FETCH_ALL_LISTING = 'FETCH_ALL_LISTING'
export const FETCH_ALL_APPROVED_LISTING = 'FETCH_ALL_APPROVED_LISTING'



export const FETCH_LISTING = 'FETCH_LISTING'